manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Paxolotl589 #new entry
      url-base: https://github.com/Paxolotl589 #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: nice-view-gem #new entry
      remote: Paxolotl589 #new entry
      revision: main #new entry
  self:
    path: config



